[2021-02-08 14:26:17,264] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_raw_monthly_data 2021-02-08T13:24:16.369759+00:00 [queued]>
[2021-02-08 14:26:17,274] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_raw_monthly_data 2021-02-08T13:24:16.369759+00:00 [queued]>
[2021-02-08 14:26:17,275] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-08 14:26:17,275] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-08 14:26:17,275] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-08 14:26:17,287] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): import_raw_monthly_data> on 2021-02-08T13:24:16.369759+00:00
[2021-02-08 14:26:17,291] {standard_task_runner.py:51} INFO - Started process 16407 to run task
[2021-02-08 14:26:17,300] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'import_raw_monthly_data', '2021-02-08T13:24:16.369759+00:00', '--job-id', '364', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpuyff9sjq']
[2021-02-08 14:26:17,303] {standard_task_runner.py:76} INFO - Job 364: Subtask import_raw_monthly_data
[2021-02-08 14:26:17,344] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.import_raw_monthly_data 2021-02-08T13:24:16.369759+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-08 14:26:17,386] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=import_raw_monthly_data
AIRFLOW_CTX_EXECUTION_DATE=2021-02-08T13:24:16.369759+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-08T13:24:16.369759+00:00
[2021-02-08 14:26:17,387] {snowflake.py:119} INFO - Executing: ['put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%raw_monthly_taxi;', "copy into raw_monthly_taxi from '@%raw_monthly_taxi/yellow_tripdata_sample_2019-03.csv.gz' ;", 'alter table RAW_MONTHLY_TAXI add column error integer;']
[2021-02-08 14:26:17,397] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_QUARANTINE_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-02-08 14:26:17,401] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.9, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-02-08 14:26:17,402] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-02-08 14:26:17,403] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-02-08 14:26:19,076] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-02-08 14:26:19,218] {cursor.py:560} INFO - query execution done
[2021-02-08 14:26:19,219] {dbapi.py:180} INFO - Running statement: put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%raw_monthly_taxi;, parameters: None
[2021-02-08 14:26:19,220] {cursor.py:537} INFO - query: [put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%...]
[2021-02-08 14:26:20,001] {cursor.py:560} INFO - query execution done
[2021-02-08 14:26:22,706] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-08 14:26:22,707] {dbapi.py:180} INFO - Running statement: copy into raw_monthly_taxi from '@%raw_monthly_taxi/yellow_tripdata_sample_2019-03.csv.gz' ;, parameters: None
[2021-02-08 14:26:22,708] {cursor.py:537} INFO - query: [copy into raw_monthly_taxi from '@%raw_monthly_taxi/yellow_tripdata_sample_2019-...]
[2021-02-08 14:26:25,525] {cursor.py:560} INFO - query execution done
[2021-02-08 14:26:25,526] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-08 14:26:25,527] {dbapi.py:180} INFO - Running statement: alter table RAW_MONTHLY_TAXI add column error integer;, parameters: None
[2021-02-08 14:26:25,527] {cursor.py:537} INFO - query: [alter table RAW_MONTHLY_TAXI add column error integer;]
[2021-02-08 14:26:26,214] {cursor.py:560} INFO - query execution done
[2021-02-08 14:26:26,216] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-08 14:26:26,216] {connection.py:438} INFO - closed
[2021-02-08 14:26:26,336] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-02-08 14:26:26,497] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=import_raw_monthly_data, execution_date=20210208T132416, start_date=20210208T132617, end_date=20210208T132626
[2021-02-08 14:26:26,522] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-08 14:26:26,584] {local_task_job.py:118} INFO - Task exited with return code 0
