[2021-01-22 11:56:13,533] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: connection_snowflake.snowflake_create 2021-01-22T10:56:05.800712+00:00 [queued]>
[2021-01-22 11:56:13,544] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: connection_snowflake.snowflake_create 2021-01-22T10:56:05.800712+00:00 [queued]>
[2021-01-22 11:56:13,544] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 11:56:13,544] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-22 11:56:13,544] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 11:56:13,552] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): snowflake_create> on 2021-01-22T10:56:05.800712+00:00
[2021-01-22 11:56:13,556] {standard_task_runner.py:51} INFO - Started process 4106 to run task
[2021-01-22 11:56:13,565] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'connection_snowflake', 'snowflake_create', '2021-01-22T10:56:05.800712+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/connection_snowflake_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmp0xmw0nkf']
[2021-01-22 11:56:13,567] {standard_task_runner.py:76} INFO - Job 23: Subtask snowflake_create
[2021-01-22 11:56:13,607] {logging_mixin.py:103} INFO - Running <TaskInstance: connection_snowflake.snowflake_create 2021-01-22T10:56:05.800712+00:00 [running]> on host admins-air.home
[2021-01-22 11:56:13,638] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=connection_snowflake
AIRFLOW_CTX_TASK_ID=snowflake_create
AIRFLOW_CTX_EXECUTION_DATE=2021-01-22T10:56:05.800712+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-22T10:56:05.800712+00:00
[2021-01-22 11:56:13,639] {snowflake.py:119} INFO - Executing: ['create table public.test_employee (id number, name string);', 'insert into public.test_employee values(1, “Sam”),(2, “Andy”),(3, “Gill”);']
[2021-01-22 11:56:13,648] {base.py:65} INFO - Using connection to: id: snowflake_conn. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-01-22 11:56:13,654] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.8, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-01-22 11:56:13,656] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-01-22 11:56:13,656] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-01-22 11:56:14,882] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-01-22 11:56:14,989] {cursor.py:560} INFO - query execution done
[2021-01-22 11:56:14,990] {dbapi.py:180} INFO - Running statement: create table public.test_employee (id number, name string);, parameters: None
[2021-01-22 11:56:14,992] {cursor.py:537} INFO - query: [create table public.test_employee (id number, name string);]
[2021-01-22 11:56:15,316] {cursor.py:560} INFO - query execution done
[2021-01-22 11:56:15,316] {dbapi.py:186} INFO - Rows affected: 1
[2021-01-22 11:56:15,317] {dbapi.py:180} INFO - Running statement: insert into public.test_employee values(1, “Sam”),(2, “Andy”),(3, “Gill”);, parameters: None
[2021-01-22 11:56:15,317] {cursor.py:537} INFO - query: [insert into public.test_employee values(1, “Sam”),(2, “Andy”),(3, “Gill”);]
[2021-01-22 11:56:15,592] {cursor.py:560} INFO - query execution done
[2021-01-22 11:56:15,609] {connection.py:438} INFO - closed
[2021-01-22 11:56:15,693] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-01-22 11:56:15,794] {taskinstance.py:1396} ERROR - 001003 (42000): 0199c730-0087-6d1e-0000-a0110002907a: SQL compilation error:
syntax error line 1 at position 43 unexpected '“S'.
syntax error line 1 at position 54 unexpected '“A'.
syntax error line 1 at position 66 unexpected '“G'.
Traceback (most recent call last):
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/airflow/providers/snowflake/operators/snowflake.py", line 121, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 612, in execute
    Error.errorhandler_wrapper(self.connection, self,
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/snowflake/connector/errors.py", line 224, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/Users/sara/p38env_airflow/lib/python3.8/site-packages/snowflake/connector/errors.py", line 179, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 0199c730-0087-6d1e-0000-a0110002907a: SQL compilation error:
syntax error line 1 at position 43 unexpected '“S'.
syntax error line 1 at position 54 unexpected '“A'.
syntax error line 1 at position 66 unexpected '“G'.
[2021-01-22 11:56:15,797] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=connection_snowflake, task_id=snowflake_create, execution_date=20210122T105605, start_date=20210122T105613, end_date=20210122T105615
[2021-01-22 11:56:15,845] {local_task_job.py:118} INFO - Task exited with return code 1
