[2021-02-16 10:24:52,576] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-14T11:45:32.707066+00:00 [queued]>
[2021-02-16 10:24:52,598] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-14T11:45:32.707066+00:00 [queued]>
[2021-02-16 10:24:52,599] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 10:24:52,599] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-16 10:24:52,599] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-16 10:24:52,611] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): GE_val_monthlychk> on 2021-02-14T11:45:32.707066+00:00
[2021-02-16 10:24:52,615] {standard_task_runner.py:51} INFO - Started process 7575 to run task
[2021-02-16 10:24:52,629] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'GE_val_monthlychk', '2021-02-14T11:45:32.707066+00:00', '--job-id', '464', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpux4pupgl']
[2021-02-16 10:24:52,635] {standard_task_runner.py:76} INFO - Job 464: Subtask GE_val_monthlychk
[2021-02-16 10:24:52,710] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-14T11:45:32.707066+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-16 10:24:52,814] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=GE_val_monthlychk
AIRFLOW_CTX_EXECUTION_DATE=2021-02-14T11:45:32.707066+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-14T11:45:32.707066+00:00
[2021-02-16 10:24:52,815] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T
[2021-02-16 10:24:52,817] {bash.py:158} INFO - Running command: cd /Users/sara/airflow/dags/demo && great_expectations checkpoint run monthlychk
[2021-02-16 10:24:52,854] {bash.py:169} INFO - Output:
[2021-02-16 10:24:57,072] {bash.py:173} INFO - Heads up! This feature is Experimental. It may change. Please give us your feedback!
[2021-02-16 10:24:57,115] {bash.py:173} INFO - You appear to be using a legacy capability with the latest config version (3.0).
[2021-02-16 10:24:57,116] {bash.py:173} INFO -     Your data context with this configuration version uses validation_operators, which are being deprecated.  Please update your configuration to be compatible with the version number 3.
[2021-02-16 10:25:21,547] {bash.py:173} INFO - Validation failed!
[2021-02-16 10:25:21,561] {bash.py:173} INFO - 
[2021-02-16 10:25:21,562] {bash.py:173} INFO - Suite Name                                   Status     Expectations met
[2021-02-16 10:25:21,563] {bash.py:173} INFO - - taxisuite                                  âœ– Failed   12 of 13 (92.31 %)
[2021-02-16 10:25:22,313] {bash.py:177} INFO - Command exited with return code 1
[2021-02-16 10:25:22,323] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-02-16 10:25:22,330] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=ge_quarantine_df_dag, task_id=GE_val_monthlychk, execution_date=20210214T114532, start_date=20210216T092452, end_date=20210216T092522
[2021-02-16 10:25:22,333] {email.py:184} INFO - Email alerting: attempt 1
[2021-02-16 10:25:23,852] {email.py:196} INFO - Sent an alert email to ['sara@acloudfrontier.com']
[2021-02-16 10:25:27,657] {local_task_job.py:118} INFO - Task exited with return code 1
