[2021-02-01 08:47:38,731] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [queued]>
[2021-02-01 08:47:38,744] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [queued]>
[2021-02-01 08:47:38,745] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 08:47:38,745] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-01 08:47:38,745] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 08:47:38,764] {taskinstance.py:1038} INFO - Executing <Task(PythonOperator): get_failed_records> on 2021-01-29T14:55:44.834581+00:00
[2021-02-01 08:47:38,786] {standard_task_runner.py:51} INFO - Started process 4787 to run task
[2021-02-01 08:47:38,786] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'get_failed_records', '2021-01-29T14:55:44.834581+00:00', '--job-id', '214', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpnntkjbhx']
[2021-02-01 08:47:38,790] {standard_task_runner.py:76} INFO - Job 214: Subtask get_failed_records
[2021-02-01 08:47:38,846] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-02-01 08:47:38,884] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=get_failed_records
AIRFLOW_CTX_EXECUTION_DATE=2021-01-29T14:55:44.834581+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-29T14:55:44.834581+00:00
[2021-02-01 08:47:38,886] {logging_mixin.py:103} INFO - {'conf': <airflow.configuration.AirflowConfigParser object at 0x7f9c6c7143a0>, 'dag': <DAG: ge_quarantine_df_dag>, 'dag_run': <DagRun ge_quarantine_df_dag @ 2021-01-29 14:55:44.834581+00:00: scheduled__2021-01-29T14:55:44.834581+00:00, externally triggered: False>, 'ds_nodash': '20210129', 'execution_date': DateTime(2021, 1, 29, 14, 55, 44, 834581, tzinfo=Timezone('+00:00')), 'inlets': [], 'macros': <module 'airflow.macros' from '/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/macros/__init__.py'>, 'next_ds': '2021-01-30', 'next_ds_nodash': '20210130', 'next_execution_date': DateTime(2021, 1, 30, 14, 55, 44, 834581, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_ds': '2021-01-28', 'prev_ds_nodash': '20210128', 'prev_execution_date': DateTime(2021, 1, 28, 14, 55, 44, 834581, tzinfo=Timezone('UTC')), 'prev_execution_date_success': <Proxy at 0x7f9c74453140 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f9c74428dc0>>, 'prev_start_date_success': <Proxy at 0x7f9c744539c0 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f9c74459f70>>, 'run_id': 'scheduled__2021-01-29T14:55:44.834581+00:00', 'task': <Task(PythonOperator): get_failed_records>, 'task_instance': <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [running]>, 'task_instance_key_str': 'ge_quarantine_df_dag__get_failed_records__20210129', 'test_mode': False, 'ti': <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [running]>, 'tomorrow_ds': '2021-01-30', 'tomorrow_ds_nodash': '20210130', 'ts': '2021-01-29T14:55:44.834581+00:00', 'ts_nodash': '20210129T145544', 'ts_nodash_with_tz': '20210129T145544.834581+0000', 'var': {'json': None, 'value': None}, 'yesterday_ds': '2021-01-28', 'yesterday_ds_nodash': '20210128', 'templates_dict': None}
[2021-02-01 08:47:38,887] {logging_mixin.py:103} INFO - 2021-01-29
[2021-02-01 08:47:38,888] {logging_mixin.py:103} INFO - {'conf': <airflow.configuration.AirflowConfigParser object at 0x7f9c6c7143a0>, 'dag': <DAG: ge_quarantine_df_dag>, 'dag_run': <DagRun ge_quarantine_df_dag @ 2021-01-29 14:55:44.834581+00:00: scheduled__2021-01-29T14:55:44.834581+00:00, externally triggered: False>, 'ds_nodash': '20210129', 'execution_date': DateTime(2021, 1, 29, 14, 55, 44, 834581, tzinfo=Timezone('+00:00')), 'inlets': [], 'macros': <module 'airflow.macros' from '/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/macros/__init__.py'>, 'next_ds': '2021-01-30', 'next_ds_nodash': '20210130', 'next_execution_date': DateTime(2021, 1, 30, 14, 55, 44, 834581, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_ds': '2021-01-28', 'prev_ds_nodash': '20210128', 'prev_execution_date': DateTime(2021, 1, 28, 14, 55, 44, 834581, tzinfo=Timezone('UTC')), 'prev_execution_date_success': <Proxy at 0x7f9c74453140 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f9c74428dc0>>, 'prev_start_date_success': <Proxy at 0x7f9c744539c0 with factory <function TaskInstance.get_template_context.<locals>.<lambda> at 0x7f9c74459f70>>, 'run_id': 'scheduled__2021-01-29T14:55:44.834581+00:00', 'task': <Task(PythonOperator): get_failed_records>, 'task_instance': <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [running]>, 'task_instance_key_str': 'ge_quarantine_df_dag__get_failed_records__20210129', 'test_mode': False, 'ti': <TaskInstance: ge_quarantine_df_dag.get_failed_records 2021-01-29T14:55:44.834581+00:00 [running]>, 'tomorrow_ds': '2021-01-30', 'tomorrow_ds_nodash': '20210130', 'ts': '2021-01-29T14:55:44.834581+00:00', 'ts_nodash': '20210129T145544', 'ts_nodash_with_tz': '20210129T145544.834581+0000', 'var': {'json': None, 'value': None}, 'yesterday_ds': '2021-01-28', 'yesterday_ds_nodash': '20210128', 'templates_dict': None}
[2021-02-01 08:47:38,889] {python.py:118} INFO - Done. Returned value was: None
[2021-02-01 08:47:38,895] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=get_failed_records, execution_date=20210129T145544, start_date=20210201T074738, end_date=20210201T074738
[2021-02-01 08:47:38,930] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-01 08:47:38,972] {local_task_job.py:118} INFO - Task exited with return code 0
