[2021-02-03 12:39:00,044] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.clean_up_monthly_data 2021-02-03T11:36:27.796224+00:00 [queued]>
[2021-02-03 12:39:00,068] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.clean_up_monthly_data 2021-02-03T11:36:27.796224+00:00 [queued]>
[2021-02-03 12:39:00,068] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-03 12:39:00,068] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-03 12:39:00,069] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-03 12:39:00,119] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): clean_up_monthly_data> on 2021-02-03T11:36:27.796224+00:00
[2021-02-03 12:39:00,124] {standard_task_runner.py:51} INFO - Started process 25255 to run task
[2021-02-03 12:39:00,137] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'clean_up_monthly_data', '2021-02-03T11:36:27.796224+00:00', '--job-id', '350', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmptg2oyzdh']
[2021-02-03 12:39:00,141] {standard_task_runner.py:76} INFO - Job 350: Subtask clean_up_monthly_data
[2021-02-03 12:39:00,221] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.clean_up_monthly_data 2021-02-03T11:36:27.796224+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-03 12:39:00,281] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=clean_up_monthly_data
AIRFLOW_CTX_EXECUTION_DATE=2021-02-03T11:36:27.796224+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-03T11:36:27.796224+00:00
[2021-02-03 12:39:00,283] {snowflake.py:119} INFO - Executing: ['alter table RAW_MONTHLY_TAXI drop column error;', 'delete from RAW_MONTHLY_TAXI;']
[2021-02-03 12:39:00,300] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_QUARANTINE_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-02-03 12:39:00,307] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.9, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-02-03 12:39:00,309] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-02-03 12:39:00,310] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-02-03 12:39:02,811] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-02-03 12:39:02,938] {cursor.py:560} INFO - query execution done
[2021-02-03 12:39:02,939] {dbapi.py:180} INFO - Running statement: alter table RAW_MONTHLY_TAXI drop column error;, parameters: None
[2021-02-03 12:39:02,940] {cursor.py:537} INFO - query: [alter table RAW_MONTHLY_TAXI drop column error;]
[2021-02-03 12:39:03,087] {cursor.py:560} INFO - query execution done
[2021-02-03 12:39:03,088] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-03 12:39:03,088] {dbapi.py:180} INFO - Running statement: delete from RAW_MONTHLY_TAXI;, parameters: None
[2021-02-03 12:39:03,089] {cursor.py:537} INFO - query: [delete from RAW_MONTHLY_TAXI;]
[2021-02-03 12:39:03,880] {cursor.py:560} INFO - query execution done
[2021-02-03 12:39:03,880] {dbapi.py:186} INFO - Rows affected: 10000
[2021-02-03 12:39:03,881] {connection.py:438} INFO - closed
[2021-02-03 12:39:03,965] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-02-03 12:39:04,092] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=clean_up_monthly_data, execution_date=20210203T113627, start_date=20210203T113900, end_date=20210203T113904
[2021-02-03 12:39:04,123] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-03 12:39:04,187] {local_task_job.py:118} INFO - Task exited with return code 0
