[2021-02-09 12:12:44,441] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-09T11:12:14.111147+00:00 [queued]>
[2021-02-09 12:12:44,460] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-09T11:12:14.111147+00:00 [queued]>
[2021-02-09 12:12:44,460] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:12:44,460] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-09 12:12:44,460] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:12:44,475] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): GE_val_monthlychk> on 2021-02-09T11:12:14.111147+00:00
[2021-02-09 12:12:44,480] {standard_task_runner.py:51} INFO - Started process 40147 to run task
[2021-02-09 12:12:44,491] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'GE_val_monthlychk', '2021-02-09T11:12:14.111147+00:00', '--job-id', '435', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpf4thoswr']
[2021-02-09 12:12:44,494] {standard_task_runner.py:76} INFO - Job 435: Subtask GE_val_monthlychk
[2021-02-09 12:12:44,537] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.GE_val_monthlychk 2021-02-09T11:12:14.111147+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-09 12:12:44,575] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=GE_val_monthlychk
AIRFLOW_CTX_EXECUTION_DATE=2021-02-09T11:12:14.111147+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-09T11:12:14.111147+00:00
[2021-02-09 12:12:44,576] {bash.py:135} INFO - Tmp dir root location: 
 /var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T
[2021-02-09 12:12:44,578] {bash.py:158} INFO - Running command: cd /Users/sara/airflow/dags/demo && python3 great_expectations/uncommitted/run_monthlychk.py
[2021-02-09 12:12:44,592] {bash.py:169} INFO - Output:
[2021-02-09 12:12:47,530] {bash.py:173} INFO - You appear to be using a legacy capability with the latest config version (3.0).
[2021-02-09 12:12:47,530] {bash.py:173} INFO -     Your data context with this configuration version uses validation_operators, which are being deprecated.  Please update your configuration to be compatible with the version number 3.
[2021-02-09 12:13:05,319] {bash.py:173} INFO - Validation failed!
[2021-02-09 12:13:06,397] {bash.py:177} INFO - Command exited with return code 1
[2021-02-09 12:13:06,405] {taskinstance.py:1396} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-02-09 12:13:06,416] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=ge_quarantine_df_dag, task_id=GE_val_monthlychk, execution_date=20210209T111214, start_date=20210209T111244, end_date=20210209T111306
[2021-02-09 12:13:06,419] {email.py:184} INFO - Email alerting: attempt 1
[2021-02-09 12:13:08,469] {email.py:196} INFO - Sent an alert email to ['sara@acloudfrontier.com']
[2021-02-09 12:13:09,598] {local_task_job.py:118} INFO - Task exited with return code 1
