[2021-02-01 08:45:35,488] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_local_dag.ge_val_01 2021-01-29T12:29:36.635367+00:00 [queued]>
[2021-02-01 08:45:35,496] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_local_dag.ge_val_01 2021-01-29T12:29:36.635367+00:00 [queued]>
[2021-02-01 08:45:35,496] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 08:45:35,496] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-01 08:45:35,496] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 08:45:35,504] {taskinstance.py:1038} INFO - Executing <Task(GreatExpectationsOperator): ge_val_01> on 2021-01-29T12:29:36.635367+00:00
[2021-02-01 08:45:35,507] {standard_task_runner.py:51} INFO - Started process 4579 to run task
[2021-02-01 08:45:35,516] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_local_dag', 'ge_val_01', '2021-01-29T12:29:36.635367+00:00', '--job-id', '206', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_local_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpmv4os315']
[2021-02-01 08:45:35,517] {standard_task_runner.py:76} INFO - Job 206: Subtask ge_val_01
[2021-02-01 08:45:35,553] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_local_dag.ge_val_01 2021-01-29T12:29:36.635367+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-02-01 08:45:35,587] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_local_dag
AIRFLOW_CTX_TASK_ID=ge_val_01
AIRFLOW_CTX_EXECUTION_DATE=2021-01-29T12:29:36.635367+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-29T12:29:36.635367+00:00
[2021-02-01 08:45:35,588] {great_expectations.py:97} INFO - Running validation with Great Expectations...
[2021-02-01 08:45:35,659] {data_context.py:1281} INFO - Setting run_name to: 20210201T074535.659401Z
[2021-02-01 08:45:35,661] {data_asset.py:636} INFO - 	4 expectation(s) included in expectation_suite.
[2021-02-01 08:45:35,669] {warnings.py:109} WARNING - /Users/sara/Dropbox/My Mac (adminâ€™s MacBook Air)/Desktop/demo/great_expectations/great_expectations/data_asset/data_asset.py:879: UserWarning: WARNING: This configuration object was built using version 0.13.3 of great_expectations, but is currently being validated by version 0.13.8+3.g9a8cbaf4.dirty.
  warnings.warn(

[2021-02-01 08:45:37,191] {great_expectations.py:141} INFO - Validation with Great Expectations successful.
[2021-02-01 08:45:37,192] {xcom.py:237} ERROR - Could not serialize the XCom value into JSON. If you are using pickles instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2021-02-01 08:45:37,193] {taskinstance.py:1396} ERROR - Object of type ValidationOperatorResult is not JSON serializable
Traceback (most recent call last):
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1303, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1827, in xcom_push
    XCom.set(
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/utils/session.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/xcom.py", line 88, in set
    value = XCom.serialize_value(value)
  File "/Users/sara/p38_demo_env/lib/python3.8/site-packages/airflow/models/xcom.py", line 235, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValidationOperatorResult is not JSON serializable
[2021-02-01 08:45:37,200] {taskinstance.py:1433} INFO - Marking task as FAILED. dag_id=ge_local_dag, task_id=ge_val_01, execution_date=20210129T122936, start_date=20210201T074535, end_date=20210201T074537
[2021-02-01 08:45:37,266] {local_task_job.py:118} INFO - Task exited with return code 1
