[2021-02-02 12:35:19,300] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_abt_nyc_taxi 2021-02-02T11:34:13.129631+00:00 [queued]>
[2021-02-02 12:35:19,306] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_abt_nyc_taxi 2021-02-02T11:34:13.129631+00:00 [queued]>
[2021-02-02 12:35:19,307] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 12:35:19,307] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-02 12:35:19,307] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-02 12:35:19,317] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): import_abt_nyc_taxi> on 2021-02-02T11:34:13.129631+00:00
[2021-02-02 12:35:19,320] {standard_task_runner.py:51} INFO - Started process 1896 to run task
[2021-02-02 12:35:19,328] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'import_abt_nyc_taxi', '2021-02-02T11:34:13.129631+00:00', '--job-id', '329', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmplb8ygmxa']
[2021-02-02 12:35:19,331] {standard_task_runner.py:76} INFO - Job 329: Subtask import_abt_nyc_taxi
[2021-02-02 12:35:19,367] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.import_abt_nyc_taxi 2021-02-02T11:34:13.129631+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2021-02-02 12:35:19,401] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=import_abt_nyc_taxi
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T11:34:13.129631+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-02T11:34:13.129631+00:00
[2021-02-02 12:35:19,402] {snowflake.py:119} INFO - Executing: ['alter table ABT_NYC_TAXI add column error integer;', 'insert into  ABT_NYC_TAXI select * from RAW_MONTHLY_TAXI where error is NULL;', 'alter table ABT_NYC_TAXI drop column error;']
[2021-02-02 12:35:19,409] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_QUARANTINE_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-02-02 12:35:19,412] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.9, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-02-02 12:35:19,413] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-02-02 12:35:19,413] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-02-02 12:35:21,006] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-02-02 12:35:21,186] {cursor.py:560} INFO - query execution done
[2021-02-02 12:35:21,187] {dbapi.py:180} INFO - Running statement: alter table ABT_NYC_TAXI add column error integer;, parameters: None
[2021-02-02 12:35:21,187] {cursor.py:537} INFO - query: [alter table ABT_NYC_TAXI add column error integer;]
[2021-02-02 12:35:21,488] {cursor.py:560} INFO - query execution done
[2021-02-02 12:35:21,489] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-02 12:35:21,491] {dbapi.py:180} INFO - Running statement: insert into  ABT_NYC_TAXI select * from RAW_MONTHLY_TAXI where error is NULL;, parameters: None
[2021-02-02 12:35:21,492] {cursor.py:537} INFO - query: [insert into  ABT_NYC_TAXI select * from RAW_MONTHLY_TAXI where error is NULL;]
[2021-02-02 12:35:22,536] {cursor.py:560} INFO - query execution done
[2021-02-02 12:35:22,537] {dbapi.py:186} INFO - Rows affected: 10000
[2021-02-02 12:35:22,538] {dbapi.py:180} INFO - Running statement: alter table ABT_NYC_TAXI drop column error;, parameters: None
[2021-02-02 12:35:22,539] {cursor.py:537} INFO - query: [alter table ABT_NYC_TAXI drop column error;]
[2021-02-02 12:35:22,734] {cursor.py:560} INFO - query execution done
[2021-02-02 12:35:22,735] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-02 12:35:22,736] {connection.py:438} INFO - closed
[2021-02-02 12:35:22,824] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-02-02 12:35:22,953] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=import_abt_nyc_taxi, execution_date=20210202T113413, start_date=20210202T113519, end_date=20210202T113522
[2021-02-02 12:35:22,971] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-02 12:35:23,003] {local_task_job.py:118} INFO - Task exited with return code 0
