[2021-02-01 12:21:02,513] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.split_data 2021-02-01T11:19:44.632902+00:00 [queued]>
[2021-02-01 12:21:02,521] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.split_data 2021-02-01T11:19:44.632902+00:00 [queued]>
[2021-02-01 12:21:02,521] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 12:21:02,521] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-02-01 12:21:02,521] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-02-01 12:21:02,530] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): split_data> on 2021-02-01T11:19:44.632902+00:00
[2021-02-01 12:21:02,534] {standard_task_runner.py:51} INFO - Started process 20514 to run task
[2021-02-01 12:21:02,543] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'split_data', '2021-02-01T11:19:44.632902+00:00', '--job-id', '259', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpfjaadtzb']
[2021-02-01 12:21:02,545] {standard_task_runner.py:76} INFO - Job 259: Subtask split_data
[2021-02-01 12:21:02,586] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.split_data 2021-02-01T11:19:44.632902+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-02-01 12:21:02,621] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=split_data
AIRFLOW_CTX_EXECUTION_DATE=2021-02-01T11:19:44.632902+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-01T11:19:44.632902+00:00
[2021-02-01 12:21:02,621] {snowflake.py:119} INFO - Executing: ['alter table QUARANTINE_DATA add column error integer;', 'insert into  QUARANTINE_DATA select * from MONTHLY_DATA where error=1;', 'alter table GENERIC_NYC_TAXI add column error integer', 'insert into  GENERIC_NYC_TAXI select * from MONTHLY_DATA where error is NULL;', 'alter table QUARANTINE_DATA drop column error;', 'alter table GENERIC_NYC_TAXI drop column error;', 'alter table MONTHLY_DATA drop column error;']
[2021-02-01 12:21:02,628] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_QUARANTINE_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-02-01 12:21:02,631] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.9, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-02-01 12:21:02,632] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-02-01 12:21:02,632] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-02-01 12:21:04,215] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-02-01 12:21:04,437] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:04,438] {dbapi.py:180} INFO - Running statement: alter table QUARANTINE_DATA add column error integer;, parameters: None
[2021-02-01 12:21:04,439] {cursor.py:537} INFO - query: [alter table QUARANTINE_DATA add column error integer;]
[2021-02-01 12:21:04,706] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:04,707] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-01 12:21:04,708] {dbapi.py:180} INFO - Running statement: insert into  QUARANTINE_DATA select * from MONTHLY_DATA where error=1;, parameters: None
[2021-02-01 12:21:04,709] {cursor.py:537} INFO - query: [insert into  QUARANTINE_DATA select * from MONTHLY_DATA where error=1;]
[2021-02-01 12:21:06,147] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:06,149] {dbapi.py:186} INFO - Rows affected: 1579
[2021-02-01 12:21:06,150] {dbapi.py:180} INFO - Running statement: alter table GENERIC_NYC_TAXI add column error integer, parameters: None
[2021-02-01 12:21:06,151] {cursor.py:537} INFO - query: [alter table GENERIC_NYC_TAXI add column error integer]
[2021-02-01 12:21:06,746] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:06,747] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-01 12:21:06,748] {dbapi.py:180} INFO - Running statement: insert into  GENERIC_NYC_TAXI select * from MONTHLY_DATA where error is NULL;, parameters: None
[2021-02-01 12:21:06,749] {cursor.py:537} INFO - query: [insert into  GENERIC_NYC_TAXI select * from MONTHLY_DATA where error is NULL;]
[2021-02-01 12:21:08,058] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:08,059] {dbapi.py:186} INFO - Rows affected: 8421
[2021-02-01 12:21:08,059] {dbapi.py:180} INFO - Running statement: alter table QUARANTINE_DATA drop column error;, parameters: None
[2021-02-01 12:21:08,060] {cursor.py:537} INFO - query: [alter table QUARANTINE_DATA drop column error;]
[2021-02-01 12:21:08,375] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:08,376] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-01 12:21:08,376] {dbapi.py:180} INFO - Running statement: alter table GENERIC_NYC_TAXI drop column error;, parameters: None
[2021-02-01 12:21:08,377] {cursor.py:537} INFO - query: [alter table GENERIC_NYC_TAXI drop column error;]
[2021-02-01 12:21:08,550] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:08,551] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-01 12:21:08,551] {dbapi.py:180} INFO - Running statement: alter table MONTHLY_DATA drop column error;, parameters: None
[2021-02-01 12:21:08,552] {cursor.py:537} INFO - query: [alter table MONTHLY_DATA drop column error;]
[2021-02-01 12:21:08,783] {cursor.py:560} INFO - query execution done
[2021-02-01 12:21:08,784] {dbapi.py:186} INFO - Rows affected: 1
[2021-02-01 12:21:08,784] {connection.py:438} INFO - closed
[2021-02-01 12:21:08,891] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-02-01 12:21:09,030] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=split_data, execution_date=20210201T111944, start_date=20210201T112102, end_date=20210201T112109
[2021-02-01 12:21:09,047] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-01 12:21:09,067] {local_task_job.py:118} INFO - Task exited with return code 0
