[2021-01-28 15:33:06,254] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_monthly_data 2021-01-28T14:32:57.616975+00:00 [queued]>
[2021-01-28 15:33:06,268] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: ge_quarantine_df_dag.import_monthly_data 2021-01-28T14:32:57.616975+00:00 [queued]>
[2021-01-28 15:33:06,269] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-28 15:33:06,269] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-28 15:33:06,269] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-28 15:33:06,280] {taskinstance.py:1038} INFO - Executing <Task(SnowflakeOperator): import_monthly_data> on 2021-01-28T14:32:57.616975+00:00
[2021-01-28 15:33:06,284] {standard_task_runner.py:51} INFO - Started process 7593 to run task
[2021-01-28 15:33:06,298] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'ge_quarantine_df_dag', 'import_monthly_data', '2021-01-28T14:32:57.616975+00:00', '--job-id', '173', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ge_quarantine_df_dag.py', '--cfg-path', '/var/folders/s2/xy3ssc8j3ks3whp2f_b8708c0000gp/T/tmpj_1c8ot9']
[2021-01-28 15:33:06,302] {standard_task_runner.py:76} INFO - Job 173: Subtask import_monthly_data
[2021-01-28 15:33:06,359] {logging_mixin.py:103} INFO - Running <TaskInstance: ge_quarantine_df_dag.import_monthly_data 2021-01-28T14:32:57.616975+00:00 [running]> on host admins-air.home
[2021-01-28 15:33:06,400] {taskinstance.py:1230} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sara@acloudfrontier.com
AIRFLOW_CTX_DAG_OWNER=sara
AIRFLOW_CTX_DAG_ID=ge_quarantine_df_dag
AIRFLOW_CTX_TASK_ID=import_monthly_data
AIRFLOW_CTX_EXECUTION_DATE=2021-01-28T14:32:57.616975+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-28T14:32:57.616975+00:00
[2021-01-28 15:33:06,401] {snowflake.py:119} INFO - Executing: ['put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%monthly_data;', "copy into monthly_data from '@%monthly_data/yellow_tripdata_sample_2019-03.csv.gz' ;"]
[2021-01-28 15:33:06,412] {base.py:65} INFO - Using connection to: id: SNOWFLAKE_QUARANTINE_DEMO. Host: dp13486.eu-west-1.snowflakecomputing.com, Port: None, Schema: PUBLIC, Login: SARA, Password: XXXXXXXX, extra: XXXXXXXX
[2021-01-28 15:33:06,416] {connection.py:215} INFO - Snowflake Connector for Python Version: 2.3.8, Python Version: 3.8.6, Platform: macOS-10.16-x86_64-i386-64bit
[2021-01-28 15:33:06,417] {connection.py:768} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2021-01-28 15:33:06,418] {connection.py:784} INFO - Setting use_openssl_only mode to False
[2021-01-28 15:33:07,798] {cursor.py:537} INFO - query: [ALTER SESSION SET autocommit=True]
[2021-01-28 15:33:07,943] {cursor.py:560} INFO - query execution done
[2021-01-28 15:33:07,944] {dbapi.py:180} INFO - Running statement: put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%monthly_data;, parameters: None
[2021-01-28 15:33:07,945] {cursor.py:537} INFO - query: [put file:////Users/sara/airflow/dags/local/yellow_tripdata_sample_2019-03.csv @%...]
[2021-01-28 15:33:08,521] {cursor.py:560} INFO - query execution done
[2021-01-28 15:33:10,559] {dbapi.py:186} INFO - Rows affected: 1
[2021-01-28 15:33:10,560] {dbapi.py:180} INFO - Running statement: copy into monthly_data from '@%monthly_data/yellow_tripdata_sample_2019-03.csv.gz' ;, parameters: None
[2021-01-28 15:33:10,561] {cursor.py:537} INFO - query: [copy into monthly_data from '@%monthly_data/yellow_tripdata_sample_2019-03.csv.g...]
[2021-01-28 15:33:11,892] {cursor.py:560} INFO - query execution done
[2021-01-28 15:33:11,893] {dbapi.py:186} INFO - Rows affected: 1
[2021-01-28 15:33:11,894] {connection.py:438} INFO - closed
[2021-01-28 15:33:11,967] {connection.py:441} INFO - No async queries seem to be running, deleting session
[2021-01-28 15:33:12,074] {taskinstance.py:1135} INFO - Marking task as SUCCESS. dag_id=ge_quarantine_df_dag, task_id=import_monthly_data, execution_date=20210128T143257, start_date=20210128T143306, end_date=20210128T143312
[2021-01-28 15:33:12,094] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-01-28 15:33:12,148] {local_task_job.py:118} INFO - Task exited with return code 0
